version: "3.7"

services:
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - seq-data:/data
    ports:
      - 3001:80
      - 5341:5341

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - sql-server-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PGM@210439
      - MSSQL_PID=Express

  core-medical-assistant:
    build:
      context: ../core
      dockerfile: ../.docker/dockerfiles/core-medical-assistant.Dockerfile
    depends_on:
      - sql-server
      - seq
    environment:
      SEQ_ADDRESS: http://seq:5341
      ConnectionStrings:MedicalAssistantDbConnection: Server=sql-server;Database=MedicalAssistant;User ID=sa;Password=PGM@210439
    volumes:
      - medical-assistant-volume:/ma/survey
    tty: true
    networks:
      - default
    restart: "no"
    ports:
      - 5001:80

volumes:
  seq-data:
  medical-assistant-volume:
  sql-server-data:

networks:
  default:
